### ISSUE TITLE
Failed to import the site module

### ISSUE THREAD

**Issue by ezeenova** [benfogle/crossenv#10]
I'm getting this error message when trying to create the virtual environment:
```
Failed to import the site module
Traceback (most recent call last):
  File "/home/alexander/apps/python-cross-compiling-example/working/crossenv/lib/site.py", line 53, in <module>
    abiflags = sysconfig.get_config_var('ABIFLAGS')
  File "/home/alexander/apps/python-cross-compiling-example/working/build-python/install/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/home/alexander/apps/python-cross-compiling-example/working/build-python/install/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/alexander/apps/python-cross-compiling-example/working/build-python/install/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_linux_.cpython-36'; '_sysconfigdata_m_linux_' is not a package
```
A module by that name does exist in host-python, but in build-python it is called _sysconfigdata_m_linux_x86_64-linux-gnu. I'm not sure which one is supposed to be imported. A comment in crossenv/lib/site.py seems to reference this problem:

> \# sysconfig isn't _quite_ set up right, because it queries from a not-yet fixed
   \# sys module. The variables that come from build_time_vars are correct, so
   \# we can safely use those. We'll re-import it later once sys is fixed.

By the way, as you can see, here I am using the example from https://github.com/benfogle/python-cross-compiling-example, but I have the same issue outside that environment.

**Comment by benfogle** [comment]
Should be fixed now. I have uploaded a fixed version to PyPI. I must have gotten very lucky in my own testing to have missed this...

The issue was that it was picking up a bad version of _sysconfigdata out of multiple possibilities. The intermittent failures were because it would just grab the first one from a set object, so on some runs it would grab a good version by chance, depending on iteration order.
