### ISSUE TITLE
Unable to build scipy.

### ISSUE THREAD

**Issue by oridb** [benfogle/crossenv#2]
I'm probably using it wrong, but after installing numpy, scipy does not build:

	$ cd scipy-1.1.0
	$ python setup.py install

	Note: if you need reliable uninstall behavior, then install
	with pip instead of using `setup.py install`:

	- `pip install .`       (from a git repo or downloaded source
				release)
	- `pip install scipy`   (last SciPy release on PyPI)

	Traceback (most recent call last):
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
	from . import multiarray
	ImportError: cannot import name 'multiarray'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	File "setup.py", line 474, in <module>
	setup_package()
	File "setup.py", line 450, in setup_package
	from numpy.distutils.core import setup
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
	from . import add_newdocs
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
	from numpy.lib import add_newdoc
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
	from .type_check import *
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
	import numpy.core.numeric as _nx
	File "/home/ori/src/py/xcenv/cross/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
	raise ImportError(msg)
	ImportError:
	Importing the multiarray numpy extension module failed.  Most
	likely you are trying to import a failed build of numpy.
	If you're working with a numpy git repo, try `git clean -xdf` (removes all
	files not under version control).  Otherwise reinstall numpy.

This seems to be the issue mentioned in the readme, where cross-expose needs to be run in order to get numpy to work, but cross-expose doesn't seem to find numpy:

       cross-expose numpy
       WARNING: 'numpy' was not found in build-python. Skipping.

Also, as mentioned in my other issue, pip doesn't work. It seems that this is also the case for cross-pip:

    (cross) ; cross-pip numpy
    Traceback (most recent call last):
      File "/home/ori/src/py/xcenv/bin/cross-pip", line 7, in <module>
        from pip._internal import main
     ModuleNotFoundError: No module named 'pip._internal'

**Comment by oridb** [comment]
Update: Realized that cross-expose was expecting me to use build-pip to install the packages. Oddly enough, `build-pip` worked just fine for me.

Now, I just need to figure out how to get the cross-built libraries into a place that scipy can find them.

**Comment by benfogle** [comment]
I don't know if this will be helpful, but I've had to do things like:

    python setup.py build_ext --libraries=<extra_libraries> install

to forcibly add libraries.

You can also use the `--env` option crossenv to set the LIBRARY_PATH environment variable, which is like adding -L flags.

Also, the [build instructions for SciPy](https://docs.scipy.org/doc/numpy-1.13.0/user/building.html) seem to indicate that a Fortran compiler is needed, which is likely another potential problem.
