### ISSUE TITLE
Shebang char limit build failure

### ISSUE THREAD

**Issue by fuzzard** [benfogle/crossenv#44]
Edit: have changed the title to be relevant to the solution in case anyone stumbles across the same limitation at a later point

Im grasping at straws here, so really not sure if you would be able to help with a failure to setup crossenv for aarch64-linux-gnu host on an x86_64-linux-gnu build.

Ive been implementing the usage of crossenv to tidy up the build system for the Kodi media centre. In the past they have been patching wildly to get modules like pillow and pycrptodome to build for the myriad of platforms (x86_64/aarch64/armv7 for android/apple/linux).

Ive implemented it, and its working great for all our build systems except our aarch64-linux target on our build server (utilising Jenkins).

We have a build python (native in our parlance) that we build from scratch for py3.8.5 (also have 3.8.8 as a test bed).
The host python (target) is again py3.8.5 (or 3.8.8 as is appropriate). All dependencies are built from source except the compiler toolchain.

The build command from the build server log for crossenv is below

```
cd aarch64-linux-gnu-debug; /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/python3 -m crossenv \
		                                        \
		                                       --env=CPATH:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/include \
		                                       --env=LIBRARY_PATH:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib \
		                                       --env=PATH:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/bin \
		                                       --env=CFLAGS:="-fPIC -DPIC -Og -g -D_DEBUG   -isystem /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/include" \
		                                       --env=CXXFLAGS:="-fPIC -DPIC -Og -g -D_DEBUG   -isystem /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/include" \
		                                       --env=LDFLAGS:="-L/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib -Wl,-rpath-link=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib  " \
		                                        \
		                                       --env=PKG_CONFIG:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/pkg-config \
		                                       --env=PKG_CONFIG_PATH:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib/pkgconfig \
		                                       --env=PKG_CONFIG_LIBDIR:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib/pkgconfig \
		                                        \
		                                       --env=PYTHONPATH:=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib/python3.8/site-packages \
		                                        \
		                                       --cc "/usr/bin/ccache /usr/bin/aarch64-linux-gnu-gcc " \
		                                       --cxx "/usr/bin/ccache /usr/bin/aarch64-linux-gnu-g++" \
		                                       --ar "/usr/bin/aarch64-linux-gnu-ar" \
		                                       -vv \
		                                       /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/bin/python3 \
	                                       /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv
```

The verbose failure we get is

```
08:25:50 WARNING: CC is a compound command (['/usr/bin/ccache', '/usr/bin/aarch64-linux-gnu-gcc'])
08:25:50 WARNING: This can cause issues for modules that don't expect it.
08:25:50 WARNING: Consider setting CC='/usr/bin/ccache' and CFLAGS='/usr/bin/aarch64-linux-gnu-gcc'
08:25:50 WARNING: CXX is a compound command (['/usr/bin/ccache', '/usr/bin/aarch64-linux-gnu-g++'])
08:25:50 WARNING: This can cause issues for modules that don't expect it.
08:25:50 WARNING: Consider setting CXX='/usr/bin/ccache' and CXXFLAGS='/usr/bin/aarch64-linux-gnu-g++'
08:25:50 INFO: Creating build-python environment
08:26:28 INFO: Creating cross-python environment
08:26:28 INFO: Installing cross-pip
08:26:28 DEBUG: Installing: ['pip==20.2.3', 'setuptools==49.2.1']
08:26:28 ERROR: [Errno 8] Exec format error: '/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/cross/bin/python3'
08:26:28 DEBUG: Traceback:
08:26:28 Traceback (most recent call last):
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/pythonmodule-crossenv/aarch64-linux-gnu-debug/crossenv/__init__.py", line 938, in main
08:26:28     builder.create(env_dir)
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/pythonmodule-crossenv/aarch64-linux-gnu-debug/crossenv/__init__.py", line 414, in create
08:26:28     self.make_cross_python(context)
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/pythonmodule-crossenv/aarch64-linux-gnu-debug/crossenv/__init__.py", line 670, in make_cross_python
08:26:28     subprocess.check_output([context.cross_env_exe, '-m', 'pip',
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/subprocess.py", line 415, in check_output
08:26:28     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/subprocess.py", line 493, in run
08:26:28     with Popen(*popenargs, **kwargs) as process:
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/subprocess.py", line 858, in __init__
08:26:28     self._execute_child(args, executable, preexec_fn, close_fds,
08:26:28   File "/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/subprocess.py", line 1706, in _execute_child
08:26:28     raise child_exception_type(errno_num, err_msg, err_filename)
08:26:28 OSError: [Errno 8] Exec format error: '/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/cross/bin/python3'
```

The kicker for me, i cant replicate it locally on a VM. I do the apple dev side of things mostly for kodi, so ive been doing android and linux build testing in a vm.
The build host python3 when built works fine when called. the crossenv build works fully for android x86_64, aarch64, armv7 as well as for Apple ios/tvos aarch64 and OSX x86_64. Our jenkins builds even work fine for Linux x86_64 and armv7

scratching my head here and really grasping at straws.
Hoping you might have some thoughts that get me on the right track to get it resolved.

**Comment by fuzzard** [comment]
A bit more info

build python (native)
```
file /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/build/bin/python3
/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/build/bin/python3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=409c724d9d67c06669bc805bd5e0fcefcc06c21b, with debug_info, not stripped
lrusak@jenkins-linux-vm2:~$ /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/build/bin/python3 --version
Python 3.8.8
```

host python (target)
```
file /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/bin/python3.8
/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/bin/python3.8: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=3235ebf8f97d84bb12e1781e0972ac14ff2268c4, with debug_info, not stripped
```

**Comment by benfogle** [comment]
So it looks like it can't run `cross-python` at `/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/cross/bin/python3`. I might have an idea: this is a Python script that relies on `build-python`, and in Linux, shebang lines are limited to 127 bytes. The path to `build-python` exceeds that by a little bit.

What is the first line of `/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/koditargetenv/cross/bin/python3`? That might help us confirm that this is what's happening.

If that is indeed the problem, then the quick fix is for you to try and shorten the path for now. More permanently, I can make `crossenv` detect this condition and emit a small bootstrap script to work around this.

**Comment by fuzzard** [comment]
That could very well explain it

https://termbin.com/smoh

I'll see if we can change that. Thanks for the pointer.

**Comment by fuzzard** [comment]
Just confirming you were absolutely spot on with the shebang char limit.
Will reduce the path on our end as a fix.

If you do find time and a suitable way to handle a long path like this, would be fantastic.

Appreciate your work with this, definitely has allowed me to clean up our build processes immensely, and simplifies a lot of things for us. Great work.
