### ISSUE TITLE
Building wheel for bcrypt did not run successfully

### ISSUE THREAD

**Issue by Sylva1n** [benfogle/crossenv#88]
Hello,

Building wheel for bcrypt did not run successfully. 

`build-pip install bcrypt`

> Collecting bcrypt
>   Using cached bcrypt-3.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (61 kB)
> Collecting six>=1.4.1
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Requirement already satisfied: cffi>=1.1 in ./venv/build/lib/python3.8/site-packages (from bcrypt) (1.15.0)
> Requirement already satisfied: pycparser in ./venv/build/lib/python3.8/site-packages (from cffi>=1.1->bcrypt) (2.21)
> Installing collected packages: six, bcrypt
> Successfully installed bcrypt-3.2.0 six-1.16.0

`pip -v install bcrypt`

> Using pip 22.0.2 from /home/sylvain/venv/build/lib/python3.8/site-packages/pip (python 3.8)
> Collecting bcrypt
>   Using cached bcrypt-3.2.0.tar.gz (42 kB)
>   Running command pip subprocess to install build dependencies
>   Collecting setuptools>=40.8.0
>     Using cached setuptools-60.6.0-py3-none-any.whl (953 kB)
>   Collecting wheel
>     Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
>   Collecting cffi>=1.1
>     Using cached cffi-1.15.0-cp38-cp38-linux_aarch64.whl
>   Collecting pycparser
>     Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
>   Installing collected packages: wheel, setuptools, pycparser, cffi
>   Successfully installed cffi-1.15.0 pycparser-2.21 setuptools-60.6.0 wheel-0.37.1
>   Installing build dependencies ... done
>   Running command Getting requirements to build wheel
>   Getting requirements to build wheel ... done
>   Running command Preparing metadata (pyproject.toml)
>   running dist_info
>   creating /tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info
>   writing /tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/PKG-INFO
>   writing dependency_links to /tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/dependency_links.txt
>   writing requirements to /tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/requires.txt
>   writing top-level names to /tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/top_level.txt
>   writing manifest file '/tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/SOURCES.txt'
>   reading manifest file '/tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   warning: no previously-included files found matching 'requirements.txt'
>   warning: no previously-included files found matching 'release.py'
>   warning: no previously-included files found matching '.travis.yml'
>   warning: no previously-included files found matching 'mypy.ini'
>   no previously-included directories found matching '.travis'
>   writing manifest file '/tmp/pip-modern-metadata-c_tiv_t7/bcrypt.egg-info/SOURCES.txt'
>   creating '/tmp/pip-modern-metadata-c_tiv_t7/bcrypt.dist-info'
>   Preparing metadata (pyproject.toml) ... done
> Requirement already satisfied: cffi>=1.1 in ./venv/cross/lib/python3.8/site-packages (from bcrypt) (1.15.0)
> Collecting six>=1.4.1
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Requirement already satisfied: pycparser in ./venv/cross/lib/python3.8/site-packages (from cffi>=1.1->bcrypt) (2.21)
> Building wheels for collected packages: bcrypt
>   Running command Building wheel for bcrypt (pyproject.toml)
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-aarch64-3.8
>   creating build/lib.linux-aarch64-3.8/bcrypt
>   copying src/bcrypt/__init__.py -> build/lib.linux-aarch64-3.8/bcrypt
>   copying src/bcrypt/__about__.py -> build/lib.linux-aarch64-3.8/bcrypt
>   copying src/bcrypt/py.typed -> build/lib.linux-aarch64-3.8/bcrypt
>   Traceback (most recent call last):
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
>       main()
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
>       return _build_backend().build_wheel(wheel_directory, config_settings,
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/build_meta.py", line 212, in build_wheel
>       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/build_meta.py", line 198, in _build_with_temp_dir
>       self.run_setup()
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
>       exec(compile(code, __file__, 'exec'), locals())
>     File "setup.py", line 46, in <module>
>       setup(
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
>       self.run_command(cmd)
>     File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
>       self.run_command('build')
>     File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/command/build_py.py", line 58, in run
>       self.build_package_data()
>     File "/home/sylvain/venv/build/lib/python3.8/site-packages/setuptools/command/build_py.py", line 132, in build_package_data
>       srcfile in self.distribution.convert_2to3_doctests):
>   AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
>   error: subprocess-exited-with-error
>   
>   × Building wheel for bcrypt (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   full command: /home/sylvain/venv/cross/bin/python3 /home/sylvain/venv/build/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpitmrotvb
>   cwd: /tmp/pip-install-t6100zow/bcrypt_6504c975743f46aea1af08b10f417bb0
>   Building wheel for bcrypt (pyproject.toml) ... error
>   ERROR: Failed building wheel for bcrypt
> Failed to build bcrypt
> ERROR: Could not build wheels for bcrypt, which is required to install pyproject.toml-based projects

How can I fix that?

Regards

**Comment by Sylva1n** [comment]
Previously I have built wheel:

`build-pip install wheel`

> Requirement already satisfied: wheel in ./venv/build/lib/python3.8/site-packages (0.37.1)

`pip -v install wheel`

> Using pip 22.0.2 from /home/sylvain/venv/build/lib/python3.8/site-packages/pip (python 3.8)
> Requirement already satisfied: wheel in ./venv/cross/lib/python3.8/site-packages (0.37.1)

**Comment by Sylva1n** [comment]
The last error is:

AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'

I tried to build **cryptography**

Same error happens:

> AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
>   error: subprocess-exited-with-error
>   
>   × Building wheel for cryptography (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   full command: /home/sylvain/venv/cross/bin/python3 /home/sylvain/venv/build/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpooyb_cgs
>   cwd: /tmp/pip-install-7x0ydyqr/cryptography_321d29036cfb41d0ae04087f397be95d
>   Building wheel for cryptography (pyproject.toml) ... error
>   ERROR: Failed building wheel for cryptography
> Failed to build cryptography
> ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

**Comment by Sylva1n** [comment]
To fix it, I needed to update both cross and build pip and setuptools packages.
