### ISSUE TITLE
python3.10 & setuptools [wip report]

### ISSUE THREAD

**Issue by xloem** [benfogle/crossenv#98]
I'm on a phone so this error report is a little messy. To update.

When I cross install, I get an error around bdist_wininst not being found. Turns out this is because a very old version of setuptools is somehow being used. When I upgrade setuptools, I get this:

`build-pip install --upgrade setuptools pkg_resources`
```
Traceback (most recent call last):
File "/home/builder/.termux-build/libtorch/src/setup.py", line 219, in <module>     import setuptools.command.build_ext                                             File "/home/builder/.termux-build/libtorch/build/python-crossenv-prefix/build/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 5, in <module>      from distutils.command.build_ext import build_ext as _du_build_ext              File "/home/builder/.termux-build/libtorch/build/python-crossenv-prefix/build/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 13, in <module>                                                                            from distutils.sysconfig import customize_compiler, get_python_version          File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked       File "<frozen importlib._bootstrap>", line 688, in _load_unlocked                 File "/home/builder/.termux-build/libtorch/build/python-crossenv-prefix/lib/site.py", line 74, in exec_module                                                         _patch_module(module, self.patch)                                               File "/home/builder/.termux-build/libtorch/build/python-crossenv-prefix/lib/site.py", line 55, in _patch_module                                                       exec(src, module.__dict__, module.__dict__)                                     File "<string>", line 13, in <module>                                           NameError: name '_init_posix' is not defined
```

**Comment by benfogle** [comment]
Hi, I am unable to reproduce this locally. What version(s) of Python are you using for both build and host? From the trace you posted, it looks like you are using termux? I wonder if that version of Python has been patched in a manner that crossenv doesn't expect.

**Comment by xloem** [comment]
This is python3.10 on the 'termux-package-builder' docker image. This should be reproducible using docker (a few 10s of GB free space needed, takes a long time to get to the failure) with:
```
git clone https://github.com/xloem/termux-packages
cd termux-packages
git checkout e0c2525f77daf6cb5ea2f5c194ef94c9bf5ef4f2
scripts/run-docker.sh ./build-package.sh libtorch
```

I'll plan to try to find some time to narrow down the issue by pulling out the relevant build commands. If I get to this without excellent luck it could take me a few months.

**Comment by xloem** [comment]
Over at termux, they confirmed that this is because the build system is running an old version of setuptools.
